#!/usr/bin/env bash
# install-hooks.sh — wire .git/hooks/pre-commit + pre-push to the audit
# pipeline. Idempotent: re-running just refreshes the hook bodies.
#
# Run once per clone:
#   bash scripts/install-hooks.sh
#
# This is opt-in (committed scripts can't auto-install themselves into
# .git/hooks). The hook bodies are also exposed as scripts/git-hook-* so
# CI can run them in non-git contexts.
set -euo pipefail
cd "$(dirname "$0")/.."

HOOK_DIR=".git/hooks"
if [ ! -d "$HOOK_DIR" ]; then
  echo "ERROR: .git/hooks not found. Run from a git checkout."
  exit 1
fi

mkdir -p "$HOOK_DIR"

cat > "$HOOK_DIR/pre-commit" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit.
# Runs cheap gates before letting the commit land:
#   - syntax (node --check)
#   - lint
#   - npm test (excludes the bundle-size step that needs dist/)
#
# Skip via:  git commit --no-verify
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "[pre-commit] node --check…"
npm run --silent syntax >/dev/null

echo "[pre-commit] eslint…"
npm run --silent lint >/dev/null

echo "[pre-commit] npm test…"
npm test >/dev/null

echo "[pre-commit] OK"
HOOK
chmod +x "$HOOK_DIR/pre-commit"

cat > "$HOOK_DIR/pre-push" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit.
# Runs the full audit:cws preflight before letting commits leave the
# local clone. Slower than pre-commit (builds dist/, validates it).
#
# Skip via:  git push --no-verify
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

echo "[pre-push] npm run audit:cws…"
npm run audit:cws >/dev/null

echo "[pre-push] OK"
HOOK
chmod +x "$HOOK_DIR/pre-push"

echo "Installed:"
echo "  $HOOK_DIR/pre-commit  (npm run syntax + lint + test)"
echo "  $HOOK_DIR/pre-push    (npm run audit:cws — full preflight)"
echo ""
echo "Skip with --no-verify if you need to commit broken WIP."
